name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.14.1 
  - jupyterlab=3.0.10  #3.5.3
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3   #22.3.1 
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  #- wandb=0.13.10
  - pip:
      - wandb==0.10.31
      - numpy==1.23.5